### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by jimmywarting**
Bringing you up to date if you wish to proceed with implementing source into create-torrent, all the other commits are just from master the master branch

More specific with this commit: https://github.com/Borewit/create-torrent/commit/c92530124b2e78d9f9a8ccceb45ae41b1a5e8878

### CODE REVIEW

**Comment by Borewit** [comment]
Thank for your effort Jimmy!
However the merge didn't went by plan. You have done a pull request to my [master branch](https://github.com/Borewit/create-torrent/tree/feature/source_string), I think it should have been either to:
- my pull-request branch: [source_string](https://github.com/Borewit/create-torrent/tree/feature/source_string).
- or the original [master](https://github.com/webtorrent/create-torrent/tree/master)
 
My mistake I merged it, and woke up just after. 
I decided to undo that change on my master branch so your changes have not been merged after all yet.

If I can contribute to add that change in, or accept a change I am open for any proposal.

**Comment by Borewit** [comment]
@jimmywarting, I merged your changes into the [source_string branch](https://github.com/Borewit/create-torrent/tree/feature/source_string), so the [pull request](https://github.com/webtorrent/create-torrent/pull/49) include your proposed changes.

Thanks for pushing the change forward!

**Comment by jimmywarting** [comment]
Sorry, picked the wrong branch, should have chosen the source_string branch

**Comment by Borewit** [comment]
No worries, good to know, so we are on the same page now.

**Pull request merged**
